version: "2"

services:
  # https://hub.docker.com/_/influxdb?tab=description
  influxdb:
    image: influxdb:2.2.0
    container_name: local-influxdb  #grafanaからアクセスするための名前
    ports:
      - 8086:8086
    environment:
    - DOCKER_INFLUXDB_INIT_MODE=setup
    - DOCKER_INFLUXDB_INIT_USERNAME=admin
    - DOCKER_INFLUXDB_INIT_PASSWORD=adminadmin
    - DOCKER_INFLUXDB_INIT_ORG=nnao45
    - DOCKER_INFLUXDB_INIT_BUCKET=lab
    - DOCKER_INFLUXDB_INIT_RETENTION=0